name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Ejecutar pruebas unitarias
        run: ./gradlew test

      - name: Construir el proyecto (build)
        run: ./gradlew build
