name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permisos para Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Ejecutar pruebas
        run: ./gradlew test

      - name: Ejecutar Build
        run: ./gradlew build